### ISSUE TITLE
running as per instructions and no output

### ISSUE THREAD

**Issue by kyleodonnell** [splunk/splunk-add-on-google-drive#4]
When I run the config ouath I get no output and nothing in var/log/configure_oauth.log.  Any ideas?
```
$ env |grep SPLUNK
SPLUNK_SERVER_NAME=Splunkd
SPLUNK_HOME=/opt/splunk-6.3.0
SPLUNK_DB=/opt/splunk-6.3.0/var/lib/splunk
SPLUNK_WEB_NAME=splunkweb
$ $SPLUNK_HOME/bin/splunk cmd python $SPLUNK_HOME/etc/apps/splunk-add-on-google-drive/bin/configure_oauth.py MyName ClientID secret
$

**Comment by kyleodonnell** [comment]
Ok I think I found the issue, but I don't know enough python to provide a patch.  There seem to be two issues:

This doesn't work:
```if __name__ == "__mainly__":```
I changed to:
```if __name__ == "__main__":```

And the if statement checking the number of args doesn't work either.  I just commented it out and I was able to authenticate.  I was able to print each of the elements of argv then I guessed the length of argv check wasn't correct and just commented it out...which worked

```
#if len(sys.argv)!=3:
#        print "Usage:./splunk cmd python ../etc/apps/googledrive_addon/bin/configure_oauth.py INPUT_NAME CLIENT_ID CLIENT_SECRET"
#        print sys.argv[1] len(sys.argv[1])
#        sys.exit()
```
Then Success!
```
Go to the following link in your browser: 
https://accounts.google.com/o/oauth2/auth?supersecretstuffhere
Enter verification code: Weeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
OAuth sign-in succeeded```

**Comment by gmelnik** [comment]
Kyle, thank you for reporting this. We have fixed this now. Will also re-release on splunkbase.
Grigori
